### ISSUE TITLE
健康上报失效

### ISSUE THREAD

**Issue by yjcreation** [Wyuyang/USTC-nCoV-Report#2]

**Comment by yuyangwang-git** [comment]
我看了一下，我这边今天依然是正常自动打卡的

另外我不确定你那边看到的报表和我的内容是否一样（因为我处于不在校状态），如果报表内容这几天并未发生变化的话，估计是网络问题导致打卡失败，这种情况确实发生过，不过由于发生概率比较低，我就没有做额外的处理，建议当天手动重新打一次卡

**Comment by yjcreation** [comment]
昨天和今天的上报都失效了，并且我刚刚手动运行了main.py，发现依然没有成功打卡，我的状态是在校状态

**Comment by yuyangwang-git** [comment]
借用同学的账号看了一下，在校生报表内容确实发生了变化，已更新 `report.ini` 文件，并更新了 `README.md`
