### ISSUE TITLE
感谢大佬的更新

### ISSUE THREAD

**Issue by wohaonan** [Wyuyang/USTC-nCoV-Report#3]
我跟我们实验室的几个小伙伴全都眼巴巴地等着新版本出来呢，今天一看又可以切换到自动模式了，当场好耶。赞一个！

**Comment by yuyangwang-git** [comment]
谢谢支持~

当初想着督促自己用GitHub，就把平时写的代码放了上去，没想到真的会有人用hhhh。后面如果发现无法正常打卡的话，十之八九又是因为学校修改了上报内容，可以直接开issue提醒我~
